In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn.linear_model as lm
import pickle
from sklearn.externals import joblib

In [3]:
df=pd.read_csv("Fuelconsumption.csv")
df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [4]:
df.describe()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
count,1067.0,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2014.0,3.346298,5.794752,13.296532,9.474602,11.580881,26.441425,256.228679
std,0.0,1.415895,1.797447,4.101253,2.794510,3.485595,7.468702,63.372304
min,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000,108.000000
25%,2014.0,2.000000,4.000000,10.250000,7.500000,9.000000,21.000000,207.000000
50%,2014.0,3.400000,6.000000,12.600000,8.800000,10.900000,26.000000,251.000000
75%,2014.0,4.300000,8.000000,15.550000,10.850000,13.350000,31.000000,294.000000
max,2014.0,8.400000,12.000000,30.200000,20.500000,25.800000,60.000000,488.000000

In [5]:
value=np.random.rand(len(df))<.8
train=df[value]
test=df[~value]

In [6]:
print(train)

      MODELYEAR   MAKE       MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
1          2014  ACURA         ILX         COMPACT         2.4          4
2          2014  ACURA  ILX HYBRID         COMPACT         1.5          4
3          2014  ACURA     MDX 4WD     SUV - SMALL         3.5          6
4          2014  ACURA     RDX AWD     SUV - SMALL         3.5          6
5          2014  ACURA         RLX        MID-SIZE         3.5          6
...         ...    ...         ...             ...         ...        ...
1062       2014  VOLVO    XC60 AWD     SUV - SMALL         3.0          6
1063       2014  VOLVO    XC60 AWD     SUV - SMALL         3.2          6
1064       2014  VOLVO    XC70 AWD     SUV - SMALL         3.0          6
1065       2014  VOLVO    XC70 AWD     SUV - SMALL         3.2          6
1066       2014  VOLVO    XC90 AWD  SUV - STANDARD         3.2          6

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
1              M6        Z                  11.2                  7.7
2             AV7        Z                   6.0                  5.8
3             AS6        Z                  12.7                  9.1
4             AS6        Z                  12.1                  8.7
5             AS6        Z                  11.9                  7.7
...           ...      ...                   ...                  ...
1062          AS6        X                  13.4                  9.8
1063          AS6        X                  13.2                  9.5
1064          AS6        X                  13.4                  9.8
1065          AS6        X                  12.9                  9.3
1066          AS6        X                  14.9                 10.2

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS
1                      9.6                        29           221
2                      5.9                        48           136
3                     11.1                        25           255
4                     10.6                        27           244
5                     10.0                        28           230
...                    ...                       ...           ...
1062                  11.8                        24           271
1063                  11.5                        25           264
1064                  11.8                        24           271
1065                  11.3                        25           260
1066                  12.8                        22           294

[846 rows x 13 columns]

In [7]:
print(test)

      MODELYEAR        MAKE                    MODEL    VEHICLECLASS  \
0          2014       ACURA                      ILX         COMPACT
6          2014       ACURA                       TL        MID-SIZE
21         2014        AUDI               A4 QUATTRO         COMPACT
26         2014        AUDI               A6 QUATTRO        MID-SIZE
28         2014        AUDI               A7 QUATTRO        MID-SIZE
...         ...         ...                      ...             ...
1037       2014  VOLKSWAGEN                    JETTA         COMPACT
1039       2014  VOLKSWAGEN                JETTA GLI         COMPACT
1045       2014  VOLKSWAGEN                   PASSAT        MID-SIZE
1049       2014  VOLKSWAGEN  PASSAT TDI CLEAN DIESEL        MID-SIZE
1054       2014  VOLKSWAGEN                  TOUAREG  SUV - STANDARD

      ENGINESIZE  CYLINDERS TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  \
0            2.0          4          AS5        Z                   9.9
6            3.5          6          AS6        Z                  11.8
21           2.0          4           M6        Z                  10.8
26           3.0          6          AS8        Z                  12.8
28           3.0          6          AS8        Z                  13.1
...          ...        ...          ...      ...                   ...
1037         2.0          4           M5        X                  10.4
1039         2.0          4           M6        Z                  10.6
1045         2.5          5           A6        X                  11.0
1049         2.0          4           M6        D                   8.0
1054         3.6          6          AS8        Z                  13.8

      FUELCONSUMPTION_HWY  FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  \
0                     6.7                   8.5                        33
6                     8.1                  10.1                        28
21                    7.5                   9.3                        30
26                    8.6                  10.9                        26
28                    8.8                  11.2                        25
...                   ...                   ...                       ...
1037                  7.2                   9.0                        31
1039                  7.4                   9.2                        31
1045                  8.0                   9.7                        29
1049                  5.4                   6.8                        42
1054                 10.3                  12.2                        23

      CO2EMISSIONS
0              196
6              232
21             214
26             251
28             258
...            ...
1037           207
1039           212
1045           223
1049           184
1054           281

[221 rows x 13 columns]

In [8]:
regr=lm.LinearRegression()
train_x=np.asanyarray(train[["ENGINESIZE","CYLINDERS","FUELCONSUMPTION_COMB"]])
train_y=np.asanyarray(train[["CO2EMISSIONS"]])
regr.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
print(regr.coef_)

[[9.96322257 7.87543124 9.95441564]]

In [10]:
print(regr.intercept_)

[62.3411819]

In [11]:
#Saving the model

joblib.dump(regr,"mymodel1.pkl")

['mymodel1.pkl']

In [12]:
test_x=np.asanyarray(test[["ENGINESIZE","CYLINDERS","FUELCONSUMPTION_COMB"]])
test_y=np.asanyarray(test[["CO2EMISSIONS"]])
prediction=regr.predict(test_x)
print(prediction)

[[198.38188489]
 [245.00464622]
 [206.3454174 ]
 [247.98656745]
 [250.97289214]
 [218.29071616]
 [217.2952746 ]
 [312.52463486]
 [312.52463486]
 [299.58389453]
 [252.96377527]
 [252.96377527]
 [293.60948376]
 [180.46393674]
 [240.02303494]
 [239.02759338]
 [201.36820958]
 [295.60388966]
 [370.91913449]
 [232.05950243]
 [295.60388966]
 [295.60388966]
 [315.51272093]
 [306.55374686]
 [251.96833371]
 [259.93186622]
 [259.93715037]
 [309.70922856]
 [212.31806678]
 [252.96905943]
 [248.98200902]
 [258.94170881]
 [334.44196312]
 [350.36902814]
 [272.8778907 ]
 [256.95082568]
 [314.53313184]
 [193.40291568]
 [184.44570299]
 [178.46776945]
 [302.74730246]
 [386.19699819]
 [392.16964758]
 [342.39756939]
 [373.26242272]
 [223.27144675]
 [319.66980905]
 [277.86126337]
 [329.62422468]
 [182.44953571]
 [194.39835725]
 [186.43130196]
 [315.52064717]
 [267.90068288]
 [270.88700757]
 [197.38115917]
 [288.80495572]
 [215.30791424]
 [249.98273474]
 [253.96450099]
 [264.91435819]
 [312.69555325]
 [215.30791424]
 [256.95082568]
 [253.96450099]
 [253.96450099]
 [203.36261548]
 [265.90979976]
 [300.75025449]
 [264.91435819]
 [338.40963829]
 [209.33174209]
 [212.32247024]
 [262.92259437]
 [302.74025692]
 [268.89700514]
 [371.26273266]
 [373.25361579]
 [185.43762179]
 [185.43762179]
 [258.94082812]
 [216.29983303]
 [193.4002736 ]
 [189.41850735]
 [246.99552935]
 [217.29967806]
 [210.32366088]
 [267.90068288]
 [273.87333227]
 [403.11950478]
 [342.39756939]
 [392.16964758]
 [269.89773086]
 [307.55711466]
 [350.3611019 ]
 [217.29879737]
 [361.3109591 ]
 [315.52064717]
 [315.52064717]
 [161.55054703]
 [211.32614799]
 [249.98185404]
 [277.85421783]
 [186.43306335]
 [209.33174209]
 [206.3454174 ]
 [214.30894991]
 [217.29879737]
 [223.27144675]
 [256.95170637]
 [249.98185404]
 [203.36349617]
 [218.29071616]
 [355.33566764]
 [349.36301826]
 [305.56358945]
 [311.53623884]
 [218.29423893]
 [226.25777144]
 [211.32262521]
 [211.32614799]
 [204.35453427]
 [272.8778907 ]
 [194.39835725]
 [186.43306335]
 [263.91803593]
 [255.95274204]
 [366.11108368]
 [388.18523924]
 [321.49065447]
 [167.52143502]
 [231.0596574 ]
 [249.98185404]
 [299.5874173 ]
 [394.1614114 ]
 [324.47433709]
 [195.3955602 ]
 [268.89700514]
 [185.44114456]
 [195.39996366]
 [185.44114456]
 [205.34821445]
 [248.98641248]
 [337.42828781]
 [339.41917093]
 [205.34997583]
 [310.54520074]
 [310.54520074]
 [199.37820714]
 [288.63844079]
 [326.47666922]
 [286.65460321]
 [343.40093719]
 [187.42850491]
 [196.38747899]
 [194.39659586]
 [189.41938804]
 [192.40571273]
 [192.40571273]
 [199.37380368]
 [192.40571273]
 [161.63160276]
 [203.35909271]
 [259.93803107]
 [237.04111371]
 [231.23585995]
 [195.39203742]
 [254.95906186]
 [201.37261304]
 [204.35893773]
 [336.42756209]
 [245.99920709]
 [252.96729804]
 [254.96170394]
 [256.95258707]
 [258.94347019]
 [244.00832397]
 [254.96170394]
 [253.96626238]
 [265.91156114]
 [228.0750941 ]
 [246.99464866]
 [243.00935963]
 [309.54359432]
 [228.0750941 ]
 [235.04318504]
 [299.58917869]
 [317.51505307]
 [335.43300122]
 [381.87427585]
 [393.8204553 ]
 [191.41203255]
 [204.35893773]
 [191.41379394]
 [191.41379394]
 [198.38188489]
 [230.24041839]
 [200.37717148]
 [175.49113238]
 [188.42570786]
 [184.44394161]
 [185.43938317]
 [223.27408883]
 [166.52599346]
 [213.31791181]
 [229.24673821]
 [239.20115385]
 [281.84038755]
 [336.42844278]
 [321.4871317 ]
 [207.34085896]
 [209.33174209]
 [220.19790148]
 [185.44114456]
 [193.40291568]
 [193.40291568]
 [203.35909271]
 [205.34997583]
 [223.18422617]
 [181.4593783 ]
 [266.90524132]]

In [13]:
predict_df=pd.read_csv("check.csv")
predict_df.head()

   ENGINESIZE  CYLINDERS  FUELCONSUMPTION_COMB  CO2EMISSIONS
0         3.2        5.8                   7.2             0

In [14]:
predict_x=np.asanyarray(predict_df[["ENGINESIZE","CYLINDERS","FUELCONSUMPTION_COMB"]])
prediction=regr.predict(predict_x)
print(prediction)

[[211.57278786]]